[package]
name = "abhishekvenkata-art"
version = "0.1.0"
edition = "2021"
description = "A library for modeling artistic concepts"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
